/* Auto-generated by tools/gen_build_info.py — do not edit. */
#ifndef BUILD_INFO_GENERATED_H
#define BUILD_INFO_GENERATED_H

#define FIRMWARE_GIT_SHA_FULL "c30cabf3d68ac023c8b6470f1c2b82f4a2cd7563"
#define GITHUB_RELEASE_OWNER "5xssro"
#define GITHUB_RELEASE_REPO "transmitter"

#endif
