#!/usr/bin/env python3
"""Generate build_info_generated.h (git SHA, GitHub owner/repo from origin)."""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


def run_git(cwd: Path, *args: str) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(cwd), *args],
            capture_output=True,
            text=True,
            check=False,
            timeout=10,
        )
        if out.returncode != 0:
            return ""
        return (out.stdout or "").strip()
    except (OSError, subprocess.TimeoutExpired):
        return ""


def parse_github_remote(url: str) -> tuple[str, str]:
    if not url:
        return ("5xssro", "transmitter")
    # git@github.com:owner/repo.git or https://github.com/owner/repo.git
    m = re.search(r"github\.com[:/]([^/]+)/([^/.]+)", url)
    if m:
        return (m.group(1), m.group(2))
    return ("5xssro", "transmitter")


def main() -> int:
    project_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
    out_path = project_dir / "build_info_generated.h"

    sha_full = run_git(project_dir, "rev-parse", "HEAD")
    if len(sha_full) != 40:
        sha_full = "0" * 40

    remote = run_git(project_dir, "config", "--get", "remote.origin.url")
    owner, repo = parse_github_remote(remote)

    lines = [
        "/* Auto-generated by tools/gen_build_info.py — do not edit. */",
        "#ifndef BUILD_INFO_GENERATED_H",
        "#define BUILD_INFO_GENERATED_H",
        "",
        f'#define FIRMWARE_GIT_SHA_FULL "{sha_full}"',
        f'#define GITHUB_RELEASE_OWNER "{owner}"',
        f'#define GITHUB_RELEASE_REPO "{repo}"',
        "",
        "#endif",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_path.relative_to(project_dir)} ({sha_full[:7]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
